version: "3.8"
services:
  db:
    image: library/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

